version: "3"

services:
  api:
    build:
      context: ./backend-dashboard
      dockerfile: Dockerfile.dev
    image: strapi_api
    container_name: strapi_backend
    ports:
      - "1337:1337"
    env_file: .env
    environment:
      - DB_NAME=$DB_NAME
      - DB_HOST=$DB_HOST
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
    volumes:
      - ./backend-dashboard:/app
      - node_modules:/app/node_modules
    restart: unless-stopped
    networks:
      - app_network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: react_client
    image: react_client
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    networks:
      - app_network
    depends_on:
      - api

networks:
  app_network:
    driver: bridge

volumes:
  node_modules:
